### ISSUE TITLE
EPIC: Drop Typescript

### ISSUE THREAD

**Issue by lemanschik** [lemanschik/src_github_microsoft_vscode#13]
We need to drop the Typescript Runtime and Build Time Dependency
- [ ] Refactor from .ts to .js
- [ ] change tsconfig.json to jsconfig.json
- [ ] Refactor Packaging into npm workspaces. 

## Enables
ESM Extensions / Plugins via Source Maps

## Why is it needed?
To make better more integrated User Expirences with a more Open Plugin System to adjust behavior 
and capabilitys.
